---
title: "chess_timer"
output: html_document
---

```{r}
library(tidyverse)
library(magick)
library(grid)
library(glue)
data <- read_csv("data/35.csv")
```




```{r}
chr_deselect <- function (quote_text){
  if (length(quote_text) > 40) {
    final_output <<- quote_text}
  else {
    if (str_sub(temp_select, chr_end, chr_end) == " "){
      final_output <<- glue(final_output, "\n", temp_select)
    } else {
      chr_end <<- chr_end - 1
      temp_select <<- str_sub(quote_text, chr_start, chr_end)
      chr_deselect(quote_text)
    }
  }
}

line_break <- function (quote_text) {
  temp_select <<- str_sub(quote_text, chr_start, chr_end)
  chr_deselect(quote_text)
  end_select <<- str_sub(quote_text, (chr_end + 1), -1)
  if (str_length(end_select) >= 40) {
    line_break(end_select)
  } else {
    final_output <<- glue(final_output, "\n", end_select)
  }
}

run_line_break <- function (input_text) {
  final_output <<- ""
  chr_start <<- 1
  chr_end <<- 40
  line_break(input_text)
}

```

```{r}

generate_images <- function (quote_num) {
vis <- image_annotate(image_blank(1000,1000, "#002d19"), run_line_break(data[quote_num, 1]), gravity = "Center", font = "Georgia", size = 40, color = "white") 
output_name <- glue("output/image_", quote_num, ".jpg")
image_write(vis, path = output_name, quality = 90)
}

for (x in 1:10) {
  generate_images(x)
}


```


